service: serverless-bank
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    ddbTableName: ${self:custom.ddbTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ '${self:custom.ddbTableName}', Arn ]

package:
  individually: true
  exclude:
    - readme.md
    - .serverless/**

plugins:
  - serverless-offline

functions:
  createAccount:
    name: serverless-bank-createAccount
    handler: api/createAccount.handler
    events:
      - http:
          method: post
          path: /account
          cors: true
    memorySize: 128
    timeout: 30
  updateBalance:
    name: serverless-bank-updateBalance
    handler: api/updateBalance.handler
    events:
      - http:
          method: put
          path: /balance
          cors: true
    memorySize: 128
    timeout: 30
  getBalance:
    name: serverless-bank-getBalance
    handler: api/getBalance.handler
    events:
      - http:
          method: get
          path: /balance
          cors: true
    memorySize: 128
    timeout: 30
  deleteAccount:
    name: serverless-bank-deleteAccount
    handler: api/deleteAccount.handler
    events:
      - http:
          method: delete
          path: /account
          cors: true
    memorySize: 128
    timeout: 30
  getAccountList:
    name: serverless-bank-getAccountList
    handler: api/getAccountList.handler
    events:
      - http:
          method: get
          path: /account/list
          cors: true
    memorySize: 128
    timeout: 30

resources:
  Resources:
    bankTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ddbTableName}
        KeySchema:
          - AttributeName: account
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: account
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  serverless-offline:
    noTimeout: true
    host: 0.0.0.0
    httpPort: 3001

  ddbTableName: bankTable